---
title: "Assignment 11"
output: pdf_document
---

This homework will help you to practice and self assess your knowledge and ability around the course concepts.  Use the answer key to assess your work.  

```{r, echo=FALSE, results = 'hide', message=FALSE, warning=FALSE}
library(tidyverse)
library(exampledata)
rinline <- function(l, r) {
  sprintf('``` %s `%s` ```', l, r)
}
```

1. Connect SQL Operations Studio to the `salesforce` database

2. The `dbo.OpportunityLineItem` table provides much of the opportunities information (from the `dbo.Opportunity` table) but breaks the opportunity into individual products with accompanying dollar amounts.  View the TOP 1000 rows from the `dbo.OpportunityLineItem` table.

3. From this table select only the columns that aren't custom (note that custom fields have a `__c` appended to the end of their name).  View only `TOP (1000)` rows.

4. Filter to get opportunities that have a `LastModifiedDate` less than or equal to '2018-01-01'.  View only `TOP (1000)` rows.

5. Add to the prior query code so to also only look at products with the `Product2Id` that is '01t70000005Qt75AAC' or '01t3900000SW3jeAAD'.  View only `TOP (1000)` rows

6. Add to the prior query code and order the results descending  on `TotalPrice`.  View only `TOP (1000)` rows

7. Determine what products have `Product2Id`s that are '01t70000005Qt75AAC' or '01t3900000SW3jeAAD'.  You will need to go to another table.  Note that the column name might not be named `Product2Id` in that table.

8. Explore the tables in the database.  Ask yourself wha the variables might mean.  If you're interested in knowing more about the non-custom variables (`__c` suffix) see https://resources.docs.salesforce.com/212/latest/en-us/sfdc/pdf/apex_api.pdf.  

    - Explore the data by making SELECT, FROM, WHERE queries.   
    - Practice exporting the data as a .csv and reading it back into R.





